### ISSUE TITLE
Use of ligatures

### ISSUE THREAD

**Issue by sangwinc** [numbas/unicode-math-normalization#4]
Christian,

I notice ｟  (2e28), https://www.fileformat.info/info/unicode/char/2e28/index.htm is mapped to a single opening parenthesis.

Are we sure no editor creates a ligature using this symbol for _double_ opening parentheses?

Chris

**Comment by christianp** [comment]
Ligatures change how a substring of characters is displayed, not the underlying encoding.

For example, [the Fira Code font](https://github.com/tonsky/FiraCode#whats-in-the-box) has ligatures for all sorts of common combinations of punctuation, rendering them as a single symbol, but that only affects the display. The string in memory will still contain the original multi-character substring.
